"""Add docks table with dock type

Revision ID: 00a25e17a50c
Revises: 05ff8bb44185
Create Date: 2026-01-19 08:48:57.835126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a25e17a50c'
down_revision: Union[str, None] = '05ff8bb44185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('dock_type', sa.Enum('STANDARD', 'COLD_CHAIN', 'VAN_ACCESS', name='docktype'), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('current_shipment_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docks_number'), 'docks', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docks_number'), table_name='docks')
    op.drop_table('docks')
    # ### end Alembic commands ###
