"""Add weight to pallets

Revision ID: 05ff8bb44185
Revises: e3b77a3b0eda
Create Date: 2026-01-19 08:24:46.120485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ff8bb44185'
down_revision: Union[str, None] = 'e3b77a3b0eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pallets', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pallets', 'weight')
    # ### end Alembic commands ###
