"""add max_weight_capacity to shipments

Revision ID: 198fcc08f0a2
Revises: b02d5180eda4
Create Date: 2026-01-19 13:58:37.285249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198fcc08f0a2'
down_revision: Union[str, None] = 'b02d5180eda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('max_weight_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'max_weight_capacity')
    # ### end Alembic commands ###
