"""...

Revision ID: 524f79a720c2
Revises: 198fcc08f0a2
Create Date: 2026-02-11 11:21:49.841915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524f79a720c2'
down_revision: Union[str, None] = '198fcc08f0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'max_weight_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'max_weight_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
