"""Link pallet to dock

Revision ID: 5efdef59d518
Revises: 00a25e17a50c
Create Date: 2026-01-19 09:03:36.659358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efdef59d518'
down_revision: Union[str, None] = '00a25e17a50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pallets', sa.Column('current_dock_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pallets', 'docks', ['current_dock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pallets', type_='foreignkey')
    op.drop_column('pallets', 'current_dock_id')
    # ### end Alembic commands ###
