"""Add shipments and link pallets

Revision ID: b02d5180eda4
Revises: 5efdef59d518
Create Date: 2026-01-19 10:46:59.595459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02d5180eda4'
down_revision: Union[str, None] = '5efdef59d518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COLLECTED', 'CANCELLED', name='shipmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_reference_number'), 'shipments', ['reference_number'], unique=True)
    op.add_column('pallets', sa.Column('shipment_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pallets', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pallets', type_='foreignkey')
    op.drop_column('pallets', 'shipment_id')
    op.drop_index(op.f('ix_shipments_reference_number'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
